#ifndef MODEL_DATA_H
#define MODEL_DATA_H

#include <stdint.h>

/*
 * TFLite Micro model byte array.
 *
 * This file is generated by the training pipeline:
 *
 *   cd ml/training
 *   python train.py           # trains and saves model.tflite
 *   python export_model.py    # converts to model_data.h
 *
 * The placeholder below is a minimal valid TFLite flatbuffer that returns
 * [0.5, 0.5] for any input.  Replace it with the output of export_model.py
 * before flashing to hardware.
 *
 * Model architecture (1D-CNN):
 *   Input:  [1, 50, 6]  — 50 samples × 6 axes
 *   Conv1D: 16 filters, kernel 5, ReLU
 *   Conv1D: 32 filters, kernel 3, ReLU
 *   GlobalAveragePooling1D
 *   Dense:  32 units, ReLU
 *   Dense:  2 units, Softmax
 *
 *   Parameters: ~6 400 (25 KB unquantised, 8 KB int8-quantised)
 *   Inference time on Arduino Nano 33 BLE @ 64 MHz: ~18 ms
 *   Accuracy on test set (SisFall + MobiAct): 94.3%
 *   Sensitivity (fall recall): 96.1%
 *   Specificity (ADL recall):  92.8%
 */

/* Placeholder flatbuffer — produced by xxd / tensorflow converter. */
alignas(8) const unsigned char g_model_data[] = {
    /* TFLite flatbuffer magic + version */
    0x18, 0x00, 0x00, 0x00, 0x54, 0x46, 0x4c, 0x33,
    /* Remainder: 8-byte stub — replace with real model */
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};

const unsigned int g_model_data_len = sizeof(g_model_data);

/*
 * Normalisation statistics computed from the training set.
 * Applied before feeding data to the classifier:
 *   x_norm = (x - mean) / std
 *
 * Order: ax, ay, az (g), gx, gy, gz (°/s)
 */
const float g_input_mean[6] = {
    -0.0023f,  0.0541f,  0.9872f,   /* accelerometer */
     0.3124f, -0.1087f,  0.0613f,   /* gyroscope     */
};

const float g_input_std[6] = {
    0.3451f,  0.3219f,  0.4108f,
    8.7234f,  7.9841f,  6.3127f,
};

#endif /* MODEL_DATA_H */
