#!/usr/bin/env python3
"""
gen_tables.py — Regenerate firmware/wavetable_gen.c when WAVE_SIZE or
SAMPLE_RATE changes.  The runtime wavetable.c uses math.h and the soft-FPU
to compute the same values at startup, so this file is optional.  Use it when
you need a flash-resident, pre-initialised table to save ~50 µs of startup
time on battery-critical builds.

Output: firmware/wavetable_gen.c
        (add to project in place of wavetable.c and remove the wavetable_init
         call from main.c — the arrays are initialised at link time).

Usage:
    python3 tools/gen_tables.py
"""

import math
import os

WAVE_SIZE   = 1024
SAMPLE_RATE = 22050


def sine_table():
    return [
        int(math.sin(2.0 * math.pi * i / WAVE_SIZE) * 32767.0)
        for i in range(WAVE_SIZE)
    ]


def midi_phase_table():
    result = []
    for n in range(128):
        freq = 440.0 * (2.0 ** ((n - 69) / 12.0))
        inc  = int(freq / SAMPLE_RATE * (2 ** 32)) & 0xFFFFFFFF
        result.append(inc)
    return result


def fmt_int16_array(name, values):
    rows = []
    row  = []
    for i, v in enumerate(values):
        row.append(f"{v:6d}")
        if len(row) == 8 or i == len(values) - 1:
            rows.append("    " + ", ".join(row) + ",")
            row = []
    body = "\n".join(rows)
    return f"const int16_t {name}[{len(values)}] = {{\n{body}\n}};"


def fmt_uint32_array(name, values):
    rows = []
    row  = []
    for i, v in enumerate(values):
        row.append(f"0x{v:08X}u")
        if len(row) == 4 or i == len(values) - 1:
            rows.append("    " + ", ".join(row) + ",")
            row = []
    body = "\n".join(rows)
    return f"const uint32_t {name}[{len(values)}] = {{\n{body}\n}};"


def main():
    sine   = sine_table()
    phases = midi_phase_table()

    lines = [
        "/* wavetable_gen.c",
        f" * Auto-generated by tools/gen_tables.py",
        f" * WAVE_SIZE={WAVE_SIZE}  SAMPLE_RATE={SAMPLE_RATE}",
        " *",
        " * To use this file instead of the runtime-initialised wavetable.c:",
        " *   1. Add wavetable_gen.c to the MPLAB X project source list.",
        " *   2. Remove wavetable.c from the project.",
        " *   3. Remove the wavetable_init() call from main.c.",
        " *   4. Change the extern declarations in wavetable.h to remove",
        " *      the 'extern' keyword (these become definitions). */",
        "",
        "#include <stdint.h>",
        "",
        fmt_int16_array("sine_table", sine),
        "",
        fmt_uint32_array("midi_phase_inc", phases),
        "",
    ]

    out_dir  = os.path.join(os.path.dirname(__file__), "..", "firmware")
    out_path = os.path.join(out_dir, "wavetable_gen.c")

    with open(out_path, "w") as f:
        f.write("\n".join(lines))

    print(f"Written {out_path}")
    print(f"  sine_table:      {len(sine)} entries  ({len(sine)*2} bytes)")
    print(f"  midi_phase_inc:  {len(phases)} entries  ({len(phases)*4} bytes)")

    # Sanity-check a few values.
    a4_inc = phases[69]
    expected_a4 = int(440.0 / SAMPLE_RATE * 2**32)
    print(f"\nSanity: A4 phase_inc = 0x{a4_inc:08X}  (expected ≈ 0x{expected_a4:08X})")
    print(f"        sine_table[256] = {sine[256]}  (expected {int(math.sin(math.pi/2)*32767)})")


if __name__ == "__main__":
    main()
