"""
Convert a trained TFLite model to a C header file for TFLite Micro.

Usage:
    python export_model.py                       # uses model_int8.tflite
    python export_model.py --model model.tflite  # full-precision model
    python export_model.py --stats training_stats.json

Output:
    ../../firmware/include/model_data.h

The generated header replaces the placeholder in model_data.h with the
real model byte array and updates the normalisation statistics.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


HEADER_TEMPLATE = """\
#ifndef MODEL_DATA_H
#define MODEL_DATA_H

#include <stdint.h>

/*
 * TFLite Micro model — generated by export_model.py.
 * Do not edit manually.
 *
 * Model: {model_name}
 * Size:  {size_bytes} bytes
 */

alignas(8) const unsigned char g_model_data[] = {{
{hex_data}
}};

const unsigned int g_model_data_len = {size_bytes}u;

/*
 * Per-axis normalisation statistics (mean and std from training set).
 * Order: ax, ay, az (g), gx, gy, gz (deg/s)
 */
const float g_input_mean[6] = {{
    {mean_accel},   /* accelerometer */
    {mean_gyro},    /* gyroscope     */
}};

const float g_input_std[6] = {{
    {std_accel},
    {std_gyro},
}};

#endif /* MODEL_DATA_H */
"""


def to_c_array(data: bytes, cols: int = 12) -> str:
    lines = []
    for i in range(0, len(data), cols):
        chunk = data[i:i + cols]
        line  = "    " + ", ".join(f"0x{b:02x}" for b in chunk)
        if i + cols < len(data):
            line += ","
        lines.append(line)
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser(description="Export TFLite model to C header")
    ap.add_argument("--model",  default="model_int8.tflite",
                    help="TFLite model file (default: model_int8.tflite)")
    ap.add_argument("--stats",  default="training_stats.json",
                    help="Normalisation stats JSON (default: training_stats.json)")
    ap.add_argument("--output",
                    default=str(Path(__file__).parent.parent.parent /
                                "firmware" / "include" / "model_data.h"))
    args = ap.parse_args()

    model_path = Path(args.model)
    if not model_path.exists():
        print(f"Model not found: {model_path}")
        print("Run train.py first to generate the model.")
        sys.exit(1)

    model_data = model_path.read_bytes()

    mean = [0.0] * 6
    std  = [1.0] * 6
    stats_path = Path(args.stats)
    if stats_path.exists():
        with open(stats_path) as f:
            stats = json.load(f)
        mean = stats["mean"]
        std  = stats["std"]
    else:
        print(f"Stats file not found ({stats_path}) — using default normalisation.")

    def fmt3(vals: list[float]) -> str:
        return ", ".join(f"{v:.6f}f" for v in vals)

    header = HEADER_TEMPLATE.format(
        model_name   = model_path.name,
        size_bytes   = len(model_data),
        hex_data     = to_c_array(model_data),
        mean_accel   = fmt3(mean[:3]),
        mean_gyro    = fmt3(mean[3:]),
        std_accel    = fmt3(std[:3]),
        std_gyro     = fmt3(std[3:]),
    )

    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(header)
    print(f"Wrote {out}  ({len(model_data):,} model bytes)")


if __name__ == "__main__":
    main()
